// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdQie8H87HAIiLnklqSTgcx71APAr_hG8',
    appId: '1:1021412303898:web:99059e63db8603dd0e5da3',
    messagingSenderId: '1021412303898',
    projectId: 'todo-app-8f6e7',
    authDomain: 'todo-app-8f6e7.firebaseapp.com',
    storageBucket: 'todo-app-8f6e7.appspot.com',
    measurementId: 'G-WYFE39P0LX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADCoCtfIHi5XffjIkZQrVbiGgH8jPcHe0',
    appId: '1:1021412303898:android:ac2aa6293e06531c0e5da3',
    messagingSenderId: '1021412303898',
    projectId: 'todo-app-8f6e7',
    storageBucket: 'todo-app-8f6e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHdNDIZh0o93sbCtSsG6TRPGT4MrcJR3U',
    appId: '1:1021412303898:ios:aa3be8028d110ffa0e5da3',
    messagingSenderId: '1021412303898',
    projectId: 'todo-app-8f6e7',
    storageBucket: 'todo-app-8f6e7.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHdNDIZh0o93sbCtSsG6TRPGT4MrcJR3U',
    appId: '1:1021412303898:ios:aa3be8028d110ffa0e5da3',
    messagingSenderId: '1021412303898',
    projectId: 'todo-app-8f6e7',
    storageBucket: 'todo-app-8f6e7.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdQie8H87HAIiLnklqSTgcx71APAr_hG8',
    appId: '1:1021412303898:web:60e9887c160395220e5da3',
    messagingSenderId: '1021412303898',
    projectId: 'todo-app-8f6e7',
    authDomain: 'todo-app-8f6e7.firebaseapp.com',
    storageBucket: 'todo-app-8f6e7.appspot.com',
    measurementId: 'G-Z04SQSQFPP',
  );
}
